services:
  - type: web
    name: bitespeed-identity-service
    env: node
    nodeVersion: 20.11.1
    buildCommand: |
      cd /opt/render/project/src
      npm install
      npm run build
      echo "=== Directory Structure ==="
      ls -la dist/
    startCommand: |
      cd /opt/render/project/src
      node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        include:
          - src/**
          - package.json
          - package-lock.json
          - tsconfig.json
        ignore:
          - README.md
          - .gitignore
          - .npmrc 