services:
  - type: web
    name: bitespeed-identity-service
    env: node
    buildCommand: npm run build:prod
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
    autoDeploy: true
    plan: free 